language: node_js
node_js:
  - "13"
  - "12"
  - "10"

install:
  - npm config set spin=false
  - npm install -g mocha coveralls
  - npm install
  - npm install graphql@$GRAPHQL_CHANNEL

script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # if coveralls doesn't have it covered

# Allow Travis tests to run in containers.
sudo: false

env:
  - GRAPHQL_CHANNEL='latest'
  - GRAPHQL_CHANNEL='rc'
